import Swoyam from "../../assets/aboutMe/leads/Swoyam.jpg";
import Raj from "../../assets/aboutMe/leads/Raj.jpg";

export const members = [
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: true,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: true,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
  {
    name: "Swoyam Siddharth Nayak",
    title: "Secretary",
    imageUrl: Swoyam,
    lead: false,
    linkedin: "https://www.linkedin.com/in/swoyam2609/",
    mail: "mailto:b121065@iiit-bh.ac.in",
  },
  {
    name: "Raj Alpha Swain",
    title: "Joint Secretary",
    imageUrl: Raj,
    lead: false,
    linkedin: "https://www.linkedin.com/in/rajalphaswain/",
    mail: "mailto:b321028@iiit-bh.ac.in",
  },
];
